apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-manager-service
  template:
    metadata:
      labels:
        app: order-manager-service
    spec:
      containers:
      - name: order-manager-service
        image: order-manager-service:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-rabbitmq:5432/order-manager
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_REDIS_HOST
          value: redis
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager-service
spec:
  selector:
    app: order-manager-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
