apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-manager-service
  template:
    metadata:
      labels:
        app: order-manager-service
    spec:
      containers:
      - name: order-manager-service
        image: gcr.io/zinc-reason-385105/order-manager-service:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://10.9.129.136:5432/order-management
        - name: SPRING_RABBITMQ_HOST
          value: 10.10.2.181
        - name: SPRING_REDIS_HOST
          value: 10.10.0.200
        - name: MESSAGING_SERVICE
          value: 10.10.2.154
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager-service
spec:
  type: LoadBalancer
  selector:
    app: order-manager-service
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
