CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email_address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    role VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT unique_username UNIQUE (name),
    CONSTRAINT unique_email UNIQUE (email_address),
    CONSTRAINT unique_number UNIQUE (phone_number)
);

CREATE TABLE "menu_item" {
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT NOT NUll,
    name VARCHAR(255) NOT NULL,
    price INTEGAR NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT pk_menu_item PRIMARY KEY (id),
    CONSTRAINT unique_username UNIQUE (name),
    CONSTRAINT restaurant_fk FOREIGN KEY (restaurant_id) REFERENCES user (id)
};

CREATE TABLE "order" {
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT NOT NUll,
    customer_id BIGINT NOT NUll,
    create_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id),
    CONSTRAINT restaurant_fk FOREIGN KEY (restaurant_id) REFERENCES user (id),
    CONSTRAINT customer_fk FOREIGN KEY (customer_id) REFERENCES user (id)
};

CREATE TABLE "order_item" {
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT NOT NUll,
    menu_item_id BIGINT NOT NUll,
    quantity BIGINT NOT NULL,
    price INTEGAR NOT NULL,
    CONSTRAINT pk_order_item PRIMARY KEY (id),
    CONSTRAINT order_fk FOREIGN KEY (order_id) REFERENCES order (id),
    CONSTRAINT menu_item_fk FOREIGN KEY (menu_item_id) REFERENCES menu_item (id),
}
